#
# docker build -t ghcr.io/bounverif/carla-client:0.9.14
# 
FROM python:3.8-slim 

ARG VERSION=0.9.14

# Add a container user (good practice)
RUN groupadd work -g 1000 \
   && useradd -ms /bin/bash carla -g 1000 -u 1000 \
   && printf "carla:carla" | chpasswd \
   && printf "carla ALL= NOPASSWD: ALL\\n" >> /etc/sudoers

USER carla
WORKDIR /home/carla/

RUN pip install --upgrade pip && pip install carla==${VERSION}
