name: Build Carla Client container image
on:
  workflow_dispatch:
  push:
    paths:
      - carla-client/Containerfile
      - .github/workflows/carla-client-build.yml # Self-trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bounverif/carla-client
  VERSION: 0.9.14

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: "VERSION=${{ env.VERSION }}"
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          file: carla-client/Containerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max